# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  
# Site settings
title: "I Bleed Cheese"
image: "/assets/images/logo.jpg"
description: > # this means to ignore newlines until "email:"
   Go Pack Or Go Home...

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/gblogo.jpg"
# blog cover
cover: "/assets/images/Lambeau.jpg"

name: 'Trey King'
author: 'Trey King'
author_image: "/assets/images/cheddar2.jpg"

paginate:	5

url: "http://ibleedcheese.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/treyking11
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
